name: Go

on:
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15 
    - run: go get -v -u github.com/docker/docker/client
    - run: go get -v -u github.com/nlopes/slack

    - name: Test
      run: go test -v ./...
